
//1.WAP to explain try catch finally mechanismusing nested try catch in different functions.

class Question_1
{

	public static void main(String [] args)
	{
		
			
		try
		{
			fun();
		}
		catch(Exception e)
		{
			System.out.println(e);
		}
		
		System.out.println("Main end");
		
	}
	
	public static void fun()
	{
		//System.out.println(10/0);
		/*
			try
			{
				System.out.println(10/0);
			}
			catch(ArithmeticException e)
			{	
				System.out.println("catch of function "+ e);
			}	
		*/
		
		try
		{
			System.out.println(10/0);
		}
		finally
		{
			System.out.println("finally of function");
		}
	}
}
